name: quantum_dart
description: An experimental package for representing quantum computing.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  matrix:
    git: git@github.com:Oxford-Hypernautics/matrix.git

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
