name: quantum_dart
description: An experimental package for representing quantum computing.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
